version: "3.8"

services:
  monitor_server:
    image: monitor_server
    container_name: monitor_server
    ports:
      - "8550:8550"
    volumes:
      - ./htpasswd:/etc/monitor_server/htpasswd:ro # Monte le fichier htpasswd

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Configuration de Nginx
    depends_on:
      - monitor_server
    networks:
      - monitor_network

networks:
  monitor_network:
    driver: bridge
